describe("organization",async()=>{
    it("create organization",async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        await expect(browser).toHaveUrlContaining("http://localhost:8888/")
        const username=await browser.$("//input[@name='user_name']")
        username.setValue("admin")
        const password=await browser.$("//input[@name='user_password']")
        password.setValue("admin")
        const loginBTN=await browser.$("//input[@id='submitButton']")
        loginBTN.click()
        await expect(browser).toHaveUrlContaining("Home")
        const organization=await browser.$("//a[.='Organizations']")
        organization.click()
        await expect(browser).toHaveUrlContaining("Accounts&action")
        const createorganization=await browser.$("//img[@title='Create Organization...']")
        createorganization.click()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        const accountname=await browser.$("//input[@name='accountname']")
        accountname.setValue("TYSS"+Math.random)
        const industry=await browser.$("//select[@name='industry']")
        industry.selectByIndex(2)
        const accounttype=await browser.$("//select[@name='accounttype']")
        accounttype.selectByVisibleText("Analyst")
        const saveBTN=await browser.$("//input[@title='Save [Alt+S]']")
        saveBTN.click()
        await expect(browser).toHaveUrlContaining("Accounts&parenttab")
        const administretor=await browser.$("//img[@src='themes/softed/images/user.PNG']")
        administretor.moveTo()
        const singout=await browser.$("//a[.='Sign Out']")
        singout.click()
    })
})