describe('product',async()=>{
    it('create_product',async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        
        const username=await browser.$("//input[@name='user_name']")
        await username.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("localhost:8888")
        await username.setValue("admin")
        const password=await browser.$("//input[@name='user_password']")
        await password.waitForDisplayed()
        await password.setValue("admin")
        const loginBTN=await browser.$("//input[@id='submitButton']")
        await loginBTN.waitForDisplayed()
        await loginBTN.click()

        const product=await browser.$("//a[.='Products']")
        await product.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Home")
        await product.click()

        const createproduct=await browser.$("//img[@title='Create Product...']")
        await createproduct.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Products&action")
        await createproduct.click()

        const productname=await browser.$("//input[@name='productname']")
        await productname.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        await productname.setValue("mobile")
        const saveBTN=await browser.$("//input[@title='Save [Alt+S]']")
        await saveBTN.waitForDisplayed()
        await saveBTN.click()
        const administretor=await browser.$("//img[@src='themes/softed/images/user.PNG']")
        await administretor.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Products&record")
        await administretor.moveTo()
        const singout=await browser.$("//a[.='Sign Out']")
        await singout.waitForDisplayed()
        await singout.click()
    })
})