const loginpage=require('../pageobjects/login.page')
const homepage=require('../pageobjects/Homepage')
const documentpage=require('../pageobjects/document_page')
const documentdetails=require('../pageobjects/document_detail_page')
describe("document",async()=>{
    it("create document",async()=>{
        await loginpage.open()
        await browser.maximizeWindow()
        await loginpage.loginToApp("admin","admin")
        await expect(browser).toHaveUrlContaining("localhost:8888")
        await homepage.documentLink()
        await expect(browser).toHaveUrlContaining("8888")
        await documentpage.create_documentButton()
        await expect(browser).toHaveUrlContaining("Documents&action")
        await documentdetails.document_details("resume","my name is manohara")
        await homepage.signout()
    })
})