describe('contact module',async()=>{
    it('create contact',async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        await expect(browser).toHaveUrlContaining("localhost:8888")
        await browser.$("//input[@name='user_name']").setValue("admin")
        await (await browser.$("//input[@name='user_password']")).setValue("admin")
        await (await browser.$("//input[@id='submitButton']")).click()
        await expect(browser).toHaveUrlContaining("Home")
        await (await browser.$("//a[.='Products']")).click()
        await expect(browser).toHaveUrlContaining("Products&action")
        await (await browser.$("//img[@title='Create Product...']")).click()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        await (await browser.$("//input[@name='productname']")).setValue("mobile")
        await (await browser.$("//input[@title='Save [Alt+S]']")).click()
        await browser.$("//img[@src='themes/softed/images/user.PNG']").moveTo()
        await browser.$("//a[.='Sign Out']").click()
        await expect(browser).toHaveUrlContaining("localhost:8888")
    })
})