describe("organization",async()=>{
    it("create organization",async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        await expect(browser).toHaveUrlContaining("http://localhost:8888/")
        await browser.$("//input[@name='user_name']").setValue("admin")
        await browser.$("//input[@name='user_password']").setValue("admin")
        await browser.$("//input[@id='submitButton']").click()
        await expect(browser).toHaveUrlContaining("Home")
        await browser.$("//a[.='Organizations']").click()
        await expect(browser).toHaveUrlContaining("Accounts&action")
        await browser.$("//img[@title='Create Organization...']").click()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        await browser.$("//input[@name='accountname']").setValue("TYSS"+Math.random)
        await browser.$("//select[@name='industry']").selectByIndex(2)
        await browser.$("//select[@name='accounttype']").selectByVisibleText("Analyst")
        await browser.$("//input[@title='Save [Alt+S]']").click()
        await expect(browser).toHaveUrlContaining("Accounts&parenttab")
        await browser.$("//img[@src='themes/softed/images/user.PNG']").moveTo()
        await browser.$("//a[.='Sign Out']").click()
    })
})