describe("compaign",async()=>{
    it("create compaign",async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        await expect(browser).toHaveUrlContaining("localhost:8888")
        await browser.$("//input[@name='user_name']").setValue("admin")
        await browser.$("//input[@name='user_password']").setValue("admin")
        await browser.$("//input[@id='submitButton']").click()
        await expect(browser).toHaveUrlContaining("Home")
        await browser.$("//a[.='More']").moveTo()
        await browser.$("//a[.='Campaigns']").click()
        await expect(browser).toHaveUrlContaining("Campaigns&action")
        await browser.$("//img[@title='Create Campaign...']").click()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        await (await browser.$("//input[@name='campaignname']")).setValue("TYC"+Math.random)
        await browser.$("//input[@title='Save [Alt+S]']").click()
        await expect(browser).toHaveUrlContaining("Campaigns&record")
        await browser.$("//img[@src='themes/softed/images/Home.PNG']").click()
        await browser.$("//img[@src='themes/softed/images/user.PNG']").moveTo()
        await browser.$("//a[.='Sign Out']").click()
    })
})