describe("compaign",async()=>{
    it("create compaign",async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        
        const username=await browser.$("//input[@name='user_name']")
        await username.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("777777")
        await username.setValue("admin")
        const password=await browser.$("//input[@name='user_password']")
        await password.waitForDisplayed()
        await password.setValue("admin")
        const loginBTN=await browser.$("//input[@id='submitButton']")
        await loginBTN.waitForClickable()
        await loginBTN.click()
        
        const more=await browser.$("//a[.='More']")
        await more.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Home")
        await more.moveTo()
        const campaign=await browser.$("//a[.='Campaigns']")
        await campaign.waitForClickable()
        await campaign.click()
        
        const create_compaign= await browser.$("//img[@title='Create Campaign...']")
        await create_compaign.waitForClickable()
        await expect(browser).toHaveUrlContaining("Campaigns&action")
        await create_compaign.click()
        
        const compaign_name=await browser.$("//input[@name='campaignname']")
        await compaign_name.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        await compaign_name.setValue("TYC"+Math.random)
        const saveBTN=await browser.$("//input[@title='Save [Alt+S]']")
        await saveBTN.waitForClickable()
        await saveBTN.click()
        
        const administretor=await browser.$("//img[@src='themes/softed/images/user.PNG']")
        await administretor.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("signout")
        await administretor.moveTo()
        const singout=await browser.$("//a[.='Sign Out']")
        await singout.waitForClickable()
        await singout.click()
    })
})