describe("Lead",async()=>{
    it("create lead",async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        
        const username=await browser.$("//input[@name='user_name']")
        await username.waitForDisplayed()
        await username.setValue("admin")
        const password=await browser.$("//input[@name='user_password']")
        await password.waitForDisplayed()
        await password.setValue("admin")
        const loginBTN=await browser.$("//input[@id='submitButton']")
        await loginBTN.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("localhost:8888")
        await loginBTN.click()
        
        const lead=await browser.$("//a[.='Leads']")
        await lead.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Home")
        await lead.click()
        
        const createlead=await browser.$("//img[@title='Create Lead...']")
        await createlead.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Leads&action")
        await createlead.click()

        const lastname=await browser.$("//input[@name='lastname']")
        await lastname.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        await lastname.setValue("reddy")
        const company=await browser.$("//input[@name='company']")
        await company.waitForDisplayed()
        await company.setValue("TYSS")
        const leadsource=await browser.$("//select[@name='leadsource']")
        await leadsource.waitForDisplayed()
        await leadsource.selectByVisibleText("Employee")
        const industry=await browser.$("//select[@name='industry']")
        await industry.waitForDisplayed()
        await industry.selectByVisibleText("Banking")
        const group=await browser.$("//input[@value='T']")
        await group.waitForDisplayed()
        await group.click()
        const groupid=await browser.$("//select[@name='assigned_group_id']")
        await groupid.waitForDisplayed()
        await groupid.selectByVisibleText("Team Selling")
        const saveBTN=await browser.$("//input[@title='Save [Alt+S]']")
        await saveBTN.waitForDisplayed()
        await saveBTN.click()

        const administretor=await browser.$("//img[@src='themes/softed/images/user.PNG']")
        await administretor.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Leads&record")
        await administretor.moveTo()
        const singout=await browser.$("//a[.='Sign Out']")
        await singout.waitForDisplayed()
        await singout.click()
    })
})