describe('contact module',async()=>{
    it('create contact with organization',async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        await expect(browser).toHaveUrlContaining("localhost:8888")
        const username=await browser.$("//input[@name='user_name']")
        username.setValue("admin")
        const password=await browser.$("//input[@name='user_password']")
        password.setValue("admin")
        const loginBTN=await browser.$("//input[@id='submitButton']")
        loginBTN.click()
        await expect(browser).toHaveUrlContaining("Home")
        const contact=await browser.$("//a[.='Contacts']")
        contact.click()
        await expect(browser).toHaveUrlContaining("Contacts&action")
        const createcontact=await browser.$("//img[@alt='Create Contact...']")
        createcontact.click()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        const lastname=await browser.$("//input[@name='lastname']")
        lastname.setValue("reddy")
        await browser.$("//img[@src='themes/softed/images/select.gif']").click()
        var window=await browser.getWindowHandles();
        await browser.switchToWindow(window[1])
        const search=await browser.$("//input[@name='search_text']")
        search.setValue("TYSS")
        const searchBTN=await browser.$("//input[@class='crmbutton small create']")
        searchBTN.click()
        await browser.pause(3000)
        const ele=await browser.$("//a[@id='1']")
        ele.click()
        await browser.switchToWindow(window[0])
        const leadsource=await browser.$("//select[@name='leadsource']")
        leadsource.selectByVisibleText("Employee")
        const saveBTN=await browser.$("//input[@title='Save [Alt+S]']")
        saveBTN.click()
        await expect(browser).toHaveUrlContaining("DetailView&module")
        const administretor=await browser.$("//img[@src='themes/softed/images/user.PNG']")
        administretor.moveTo()
        const singout=await browser.$("//a[.='Sign Out']")
        singout.click()
    })
})