const loginPage=require('../pageobjects/login.page')
const homepage=require('../pageobjects/Homepage')
const campaignpage=require('../pageobjects/create_campaign_page')
const create_campagin_detail_page=require('../pageobjects/create_compagin_detail_page')

describe("compaign",async()=>{
    it("create compaign",async()=>{
        await loginPage.open()
        await browser.maximizeWindow()
        await loginPage.loginToApp("admin","admin")
        await homepage.moreLink()
        await expect(browser).toHaveUrlContaining("Home")
        await homepage.campaignLink()
        await campaignpage.create_compaignButton()
        await expect(browser).toHaveUrlContaining("Campaigns&action")
        await create_campagin_detail_page.compaign_details("TYC")
        await expect(browser).toHaveUrlContaining("8888")
        await homepage.signout()
    })
})