describe('contact module',async()=>{
    it('create contact',async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        // await expect(browser).toHaveTitleContaining("vtiger")
        const username=await browser.$("//input[@name='user_name']")
        username.setValue("admin")
        const password=await browser.$("//input[@name='user_password']")
        password.waitForDisplayed()
        password.setValue("admin")
        const submitBTN=await browser.$("//input[@id='submitButton']")
        submitBTN.click()
        // await expect(browser).toHaveUrlContaining("localhost:8888")
        const contactBTN=await browser.$("//a[.='Contacts']")
        contactBTN.waitForClickable()
        contactBTN.click()
        // await expect(browser).toHaveTitleContaining("Contacts")
        const create_contact=await browser.$("//img[@alt='Create Contact...']")
        create_contact.waitForClickable()
        create_contact.click()
        // await expect(browser).toHaveTitleContaining("Contacts")
        const lastname=await browser.$("//input[@name='lastname']")
        lastname.waitForDisplayed()
        lastname.setValue("reddy")
        const saveBTN=await browser.$("//input[@title='Save [Alt+S]']")
        saveBTN.waitForDisplayed()
        saveBTN.click()
        // await expect(browser).toHaveTitleContaining("Contacts")
        var lastname1=await (await browser.$("//span[@class='dvHeaderText']")).getText
        await console.log(lastname1);
        const administretor=await browser.$("//img[@src='themes/softed/images/user.PNG']")
        administretor.waitForDisplayed()
        administretor.moveTo()
        const singout=await browser.$("//a[.='Sign Out']")
        singout.waitForDisplayed()
        singout.click()
        // await expect(browser).toHaveTitleContaining("vtiger")
    })
})
