describe("document",async()=>{
    it("create document",async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()

        const username=await browser.$("//input[@name='user_name']")
        await username.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("localhost:8888")
        await username.setValue("admin")
        const password=await browser.$("//input[@name='user_password']")
        await password.waitForDisplayed()
        await password.setValue("admin")
        const loginBTN=await browser.$("//input[@id='submitButton']")
        await loginBTN.waitForDisplayed()
        await loginBTN.click()
        
        await expect(browser).toHaveUrlContaining("Home")
        const documentBTN=await browser.$("//a[.='Documents']")
        await documentBTN.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Home")
        await documentBTN.click()

        const createDocument=await browser.$("//img[@title='Create Document...']")
        await createDocument.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Documents&action")
        await createDocument.click()
        
        const documentname=await browser.$("//input[@class='detailedViewTextBox']")
        await documentname.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        await documentname.setValue("resume")
        const fream=await browser.$("//iframe")
        await fream.waitForDisplayed()
        await browser.switchToFrame(0)
        const data=await browser.$("//body[@class='cke_show_borders']")
        await data.waitForDisplayed()
        await data.setValue("my name is manohara")
        await browser.keys(['control','a'])
        await browser.switchToParentFrame()
        const bold=await browser.$("//a[@id='cke_5']")
        await bold.waitForDisplayed()
        await bold.click()
        const italic=await browser.$("//a[@id='cke_6']")
        await italic.waitForDisplayed()
        await italic.click()
        const filepath=await browser.$("//input[@name='filename']")
        await filepath.waitForDisplayed()
        await filepath.uploadFile("C:/Users/HARISH/Downloads/manohara.resume1 (1)")
        const saveBTN=await browser.$("//input[@title='Save [Alt+S]']")
        await saveBTN.waitForDisplayed()
        await saveBTN.click()
        
        const administretor=await browser.$("//img[@src='themes/softed/images/user.PNG']")
        await administretor.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("iew&module")
        await administretor.moveTo()
        const singout=await browser.$("//a[.='Sign Out']")
        await singout.waitForDisplayed()
        await singout.click()
    })
})