describe("compaign",async()=>{
    it("create compaign with product",async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        await expect(browser).toHaveUrlContaining("localhost:8888")
        const username=await browser.$("//input[@name='user_name']")
        username.setValue("admin")
        const password=await browser.$("//input[@name='user_password']")
        password.setValue("admin")
        const loginBTN=await browser.$("//input[@id='submitButton']")
        loginBTN.click()
        await expect(browser).toHaveUrlContaining("Home")
        const product=await browser.$("//a[.='Products']")
        product.click()
        await expect(browser).toHaveUrlContaining("Products&action")
        const createproduct=await browser.$("//img[@title='Create Product...']")
        createproduct.click()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        const productname=await browser.$("//input[@name='productname']")
        productname.setValue("mobile")
        const saveBTN=await browser.$("//input[@title='Save [Alt+S]']")
        saveBTN.click()
        const more=await browser.$("//a[.='More']")
        more.moveTo()
        const campaign=await browser.$("//a[.='Campaigns']")
        campaign.click()
        await expect(browser).toHaveUrlContaining("Campaigns&action")
        const createcampaign=await browser.$("//img[@title='Create Campaign...']")
        createcampaign.click()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        const campaignname=await browser.$("//input[@name='campaignname']")
        campaignname.setValue("TYC"+Math.random)
        const group=await browser.$("//input[@value='T']")
        group.click()
        const groupid=await browser.$("//select[@name='assigned_group_id']")
        groupid.selectByVisibleText("Support Group")
        await browser.$("//img[@src='themes/softed/images/select.gif']").click()
        var window=await browser.getWindowHandles();
        await browser.switchToWindow(window[1])
        const seaarch= await browser.$("//input[@name='search_text']")
        seaarch.setValue("mobile")
        const searchBTN=await browser.$("//input[@name='search']")
        searchBTN.click()
        const ele= await browser.$("//a[@id='1']")
        ele.click()
        await browser.switchToWindow(window[0])
        const saveBTN1=await browser.$("//input[@title='Save [Alt+S]']")
        saveBTN1.click()
        await expect(browser).toHaveUrlContaining("Campaigns&record")
        await browser.$("//td[@class='dvtCellInfo']").getText()=="mobile"
        const administretor=await browser.$("//img[@src='themes/softed/images/user.PNG']")
        administretor.moveTo()
        const singout=await browser.$("//a[.='Sign Out']")
        singout.click()
    })
})