describe("compaign",async()=>{
    it("create compaign with product",async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        
        const username=await browser.$("//input[@name='user_name']")
        await username.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("localhost:8888")
        await username.setValue("admin")
        const password=await browser.$("//input[@name='user_password']")
        await password.waitForDisplayed()
        await password.setValue("admin")
        const loginBTN=await browser.$("//input[@id='submitButton']")
        await loginBTN.waitForDisplayed()
        await loginBTN.click()

        const product=await browser.$("//a[.='Products']")
        await product.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Home")
        await product.click()

        const createproduct=await browser.$("//img[@title='Create Product...']")
        await createproduct.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Products&action")
        await createproduct.click()

        const productname=await browser.$("//input[@name='productname']")
        await productname.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        await productname.setValue("mobile")
        const saveBTN=await browser.$("//input[@title='Save [Alt+S]']")
        await saveBTN.waitForDisplayed()
        await saveBTN.click()
        const more=await browser.$("//a[.='More']")
        await more.waitForDisplayed()
        await more.moveTo()
        const campaign=await browser.$("//a[.='Campaigns']")
        await campaign.waitForDisplayed()
        await campaign.click()
        
        const createcampaign=await browser.$("//img[@title='Create Campaign...']")
        await createcampaign.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Campaigns&action")
        await createcampaign.click()

        const campaignname=await browser.$("//input[@name='campaignname']")
        await campaignname.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        await campaignname.setValue("TYC"+Math.random)
        const group=await browser.$("//input[@value='T']")
        await group.click()
        const groupid=await browser.$("//select[@name='assigned_group_id']")
        await groupid.selectByVisibleText("Support Group")
        const img=await browser.$("//img[@src='themes/softed/images/select.gif']")
        await img.waitForDisplayed()
        await img.click()
        var window=await browser.getWindowHandles();
        await browser.switchToWindow(window[1])
        const search= await browser.$("//input[@name='search_text']")
        await search.waitForDisplayed()
        await search.setValue("mobile")
        const searchBTN=await browser.$("//input[@name='search']")
        await searchBTN.waitForDisplayed()
        await searchBTN.click()
        const ele= await browser.$("//a[@id='1']")
        await ele.waitForDisplayed()
        await ele.click()
        await browser.switchToWindow(window[0])
        const saveBTN1=await browser.$("//input[@title='Save [Alt+S]']")
        await saveBTN1.waitForDisplayed()
        await saveBTN1.click()

        await browser.$("//td[@class='dvtCellInfo']").getText()=="mobile"
        const administretor=await browser.$("//img[@src='themes/softed/images/user.PNG']")
        await administretor.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Campaigns&record")
        await administretor.moveTo()
        const singout=await browser.$("//a[.='Sign Out']")
        await singout.waitForDisplayed()
        await singout.click()
    })
})