describe('contact module',async()=>{
    it('create contact with organization',async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        
        const username=await browser.$("//input[@name='user_name']")
        await username.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("localhost:8888")
        await username.setValue("admin")
        const password=await browser.$("//input[@name='user_password']")
        await password.waitForDisplayed()
        await password.setValue("admin")
        const loginBTN=await browser.$("//input[@id='submitButton']")
        await loginBTN.waitForDisplayed()
        await loginBTN.click()
        
        const contact=await browser.$("//a[.='Contacts']")
        await contact.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Home")
        await contact.click()

        const createcontact=await browser.$("//img[@alt='Create Contact...']")
        await createcontact.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("Contacts&action")
        await createcontact.click()

        const lastname=await browser.$("//input[@name='lastname']")
        await lastname.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        await lastname.setValue("reddy")
        const img=await browser.$("//img[@src='themes/softed/images/select.gif']")
        await img.waitForDisplayed()
        await img.click()
        var window=await browser.getWindowHandles();
        await browser.switchToWindow(window[1])
        const search=await browser.$("//input[@name='search_text']")
        await search.waitForDisplayed()
        await search.setValue("TYSS")
        const searchBTN=await browser.$("//input[@class='crmbutton small create']")
        await search.waitForDisplayed()
        await searchBTN.click()
        const ele=await browser.$("//a[@id='1']")
        await ele.waitForDisplayed()
        await ele.click()
        await browser.switchToWindow(window[0])
        const leadsource=await browser.$("//select[@name='leadsource']")
        await leadsource.waitForDisplayed()
        await leadsource.selectByVisibleText("Employee")
        const saveBTN=await browser.$("//input[@title='Save [Alt+S]']")
        await saveBTN.waitForDisplayed()
        await saveBTN.click()

        const administretor=await browser.$("//img[@src='themes/softed/images/user.PNG']")
        await administretor.waitForDisplayed()
        await expect(browser).toHaveUrlContaining("DetailView&module")
        await administretor.moveTo()
        const singout=await browser.$("//a[.='Sign Out']")
        await singout.waitForDisplayed()
        await singout.click()
    })
})