describe('contact module',async()=>{
    it('create contact with organization',async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        await expect(browser).toHaveUrlContaining("localhost:8888")
        await browser.$("//input[@name='user_name']").setValue("admin")
        await browser.$("//input[@name='user_password']").setValue("admin")
        await (await browser.$("//input[@id='submitButton']")).click()
        await expect(browser).toHaveUrlContaining("Home")
        await browser.$("//a[.='Contacts']").click()
        await expect(browser).toHaveUrlContaining("Contacts&action")
        await browser.$("//img[@alt='Create Contact...']").click()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        await browser.$("//input[@name='lastname']").setValue("reddy")
        await browser.$("//img[@src='themes/softed/images/select.gif']").click()
        var window=await browser.getWindowHandles();
        await browser.switchToWindow(window[1])
        await browser.$("//input[@name='search_text']").setValue("TYSS")
        await browser.$("//input[@class='crmbutton small create']").click()
        await browser.pause(3000)
        await browser.$("//a[@id='1']").click()
        await browser.switchToWindow(window[0])
        await (await browser.$("//select[@name='leadsource']")).selectByVisibleText("Employee")
        await browser.$("//input[@title='Save [Alt+S]']").click()
        await expect(browser).toHaveUrlContaining("DetailView&module")
        await browser.$("//img[@src='themes/softed/images/user.PNG']").moveTo()
        await browser.$("//a[.='Sign Out']").click()
    })
})