describe("document",async()=>{
    it("create document",async()=>{
        await browser.url('http://localhost:8888/')
        await browser.maximizeWindow()
        await expect(browser).toHaveUrlContaining("localhost:8888")
        const username=await browser.$("//input[@name='user_name']")
        username.setValue("admin")
        const password=await browser.$("//input[@name='user_password']")
        password.setValue("admin")
        const loginBTN=await browser.$("//input[@id='submitButton']")
        loginBTN.click()
        await expect(browser).toHaveUrlContaining("Home")
        const documentBTN=await browser.$("//a[.='Documents']")
        documentBTN.click()
        await expect(browser).toHaveUrlContaining("Documents&action")
        const createDocument=await browser.$("//img[@title='Create Document...']")
        createDocument.click()
        await expect(browser).toHaveUrlContaining("EditView&return_action")
        const documentname=await browser.$("//input[@class='detailedViewTextBox']")
        documentname.setValue("resume")
        const fream=await browser.$("//iframe")
        fream.waitForDisplayed()
        await browser.switchToFrame(0)
        const data=await browser.$("//body[@class='cke_show_borders']")
        data.setValue("my name is manohara")
        await browser.keys(['control','a'])
        await browser.switchToParentFrame()
        const bold=await browser.$("//a[@id='cke_5']")
        bold.click()
        const italic=await browser.$("//a[@id='cke_6']")
        italic.click()
        const filepath=await browser.$("//input[@name='filename']")
        filepath.uploadFile("C:\Users\HARISH\Downloads\manohara.resume1 (1)")
        const saveBTN=await browser.$("//input[@title='Save [Alt+S]']")
        saveBTN.click()
        await expect(browser).toHaveUrlContaining("iew&module")
        const administretor=await browser.$("//img[@src='themes/softed/images/user.PNG']")
        administretor.moveTo()
        const singout=await browser.$("//a[.='Sign Out']")
        singout.click()
    })
})